# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTerapeutico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('cantidad', models.TextField()),
                ('presentacion', models.TextField()),
                ('causes', models.ManyToManyField(blank=True, null=True, related_name='medicamento_causes', to='causes.Causes')),
                ('grupoterapeutico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.GrupoTerapeutico')),
            ],
        ),
    ]
