# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigopostal', models.CharField(max_length=10)),
                ('nom_asenta', models.CharField(max_length=250)),
                ('tipo_asenta', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('clave', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=250)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=250)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('iniciales', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Municipio'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Municipio'),
        ),
    ]
