# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaPracticaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('fechapub', models.CharField(blank=True, max_length=20, null=True)),
                ('eyrpdf', models.FileField(blank=True, null=True, upload_to='gpc')),
                ('grrpdf', models.FileField(blank=True, null=True, upload_to='gpc')),
                ('causes', models.ManyToManyField(blank=True, null=True, related_name='normatividad_causes', to='causes.Causes')),
            ],
        ),
    ]
