# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionIncluida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('atenciones', models.ManyToManyField(blank=True, null=True, to='causes.AtencionIncluida')),
            ],
        ),
        migrations.CreateModel(
            name='Conglomerado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TabuladorCauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costofijo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costovariable', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costototal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('terapiaintensiva', models.BooleanField(default=False)),
                ('causes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causes.Causes')),
            ],
        ),
        migrations.AddField(
            model_name='causes',
            name='conglomerado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causes.Conglomerado'),
        ),
    ]
