# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliaresdx', '0001_initial'),
        ('medicamentos', '0001_initial'),
        ('causes', '0001_initial'),
        ('documentacionmedica', '0001_initial'),
        ('cies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCAUSES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxdx', models.ManyToManyField(blank=True, null=True, to='auxiliaresdx.AuxiliarDx')),
                ('caus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='causes.Causes')),
                ('diags', models.ManyToManyField(blank=True, null=True, to='cies.Cie10')),
                ('gpcs', models.ManyToManyField(blank=True, null=True, to='documentacionmedica.GuiaPracticaClinica')),
                ('meds', models.ManyToManyField(blank=True, null=True, to='medicamentos.Medicamento')),
                ('procs', models.ManyToManyField(blank=True, null=True, to='cies.Cie9MC')),
            ],
        ),
    ]
