# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geograficos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_cel', models.CharField(max_length=100)),
                ('Num_Tel_Casa', models.CharField(max_length=10)),
                ('Estado_Civil', models.CharField(max_length=100)),
                ('Escolaridad', models.CharField(max_length=100)),
                ('Ocupacion', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('Dialecto', models.CharField(max_length=100)),
                ('Grupo_Etnico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('Num_int', models.CharField(max_length=100)),
                ('Num_Ext', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('expediente', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('no_afiliacion', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=250)),
                ('apaterno', models.CharField(max_length=250)),
                ('amaterno', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.CharField(choices=[(b'mas', b'Masculino'), (b'fem', b'Feminino')], max_length=10)),
                ('fec_nac', models.DateField()),
                ('curp', models.CharField(max_length=20)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Entidad')),
                ('entidad_nac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_nac', to='geograficos.Entidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geograficos.Municipio')),
                ('nacionalidad', models.ForeignKey(default=b'223', on_delete=django.db.models.deletion.CASCADE, to='geograficos.Nacionalidad')),
            ],
        ),
        migrations.AddField(
            model_name='datospaciente',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Paciente'),
        ),
    ]
