# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_domiciliopaciente_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Dialecto',
            new_name='dialecto',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Escolaridad',
            new_name='escolaridad',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Estado_Civil',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Grupo_Etnico',
            new_name='grupo_etnico',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Num_Tel_Casa',
            new_name='num_tel_casa',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Numero_cel',
            new_name='numero_cel',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Ocupacion',
            new_name='ocupacion',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='email',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='Religion',
            new_name='religion',
        ),
    ]
