# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20160317_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_internado', models.DateField()),
                ('diagnostico_ingreso', models.CharField(choices=[(b'ABANDONO SOCIAL +DHE + PB. IRC', b'ABANDONO SOCIAL +DHE + PB. IRC'), (b'diag2', b'ABCESO +VALVULA'), (b'diag3', b'ABCESO EN GLUTEO DERECHO'), (b'diag4', b'ABCESO ESCAPULAR IZQUIERDO'), (b'diag5', b'ABCESO TESTICULAR'), (b'diag6', b'ABORTO DIFERIDO'), (b'diag7', b'ABORTO EN EVOLUCION'), (b'diag8', b'ABORTO INCOMPLETO'), (b'diag9', b'ABSESO EN CUELLO'), (b'diag10', b'ABSESO MAXILAR'), (b'diag11', b'AFIXIA TAQUITRANSITORIO'), (b'diag12', b'AGREDIDA POR TERCERAS PERSONAS'), (b'diag13', b'ALCOHOLISMO CRONICO PB EVC HEMORRAGICO SANGRADO DE TD ALTO DESIDRATACI'), (b'diag14', b'ALERGICA A  PICADURA DE ALACRAN O ARA\xc3\x91A'), (b'diag15', b'AMENAZA DE ABORTO'), (b'diag16', b'AMENAZA DE ABORTO DE 10 SDG'), (b'diag17', b'AMENAZA DE PARTO PREMATURO'), (b'diag18', b'AMENZA DE PARTO PRETERMINO'), (b'diag19', b'AMIGDALECTOMIA'), (b'diag20', b'AMPUTACION DE 1 Y 2 ORTEJO DE PIE IZQUIERDA'), (b'diag21', b'ANASARACA + DERRAME PLEURAL BILATERAL + EPOC AGUADIZADO'), (b'diag22', b'ANASARCA +DESNUTRICION + PB.INSUF.CARDIACA'), (b'diag23', b'ANEMIA'), (b'diag24', b'ANEMIA CRONICAREMITIDA+ADENOCARCINOMA RECTAL INFILTRANTE'), (b'diag25', b'ANEMIA DE LACTANTES'), (b'diag26', b'ANEMIA SECUNDARIA A HEMORRAGIA UTERINA A MIOMATOSIS'), (b'diag27', b'ANEMIA SEVERA'), (b'diag28', b'ANO IMPERFORADO'), (b'diag29', b'APENDICECTOMIA'), (b'diag30', b'APENDICECTOMIA+ILITIS EN TRATAMIENTO'), (b'diag31', b'APENDICITIS AGUDA'), (b'diag32', b'APENDICITIS AGUDA+B TEPATOMA DE OVARIO DERRECHO+PO.LAPE'), (b'diag33', b'ARTRITIS GOTOSA RODILLA IZQ.'), (b'diag34', b'ASFIXIA PERINATAL'), (b'diag35', b'ASMA BRONQUIAL'), (b'diag36', b'ASMA BRONQUIAL AGUDIZADA'), (b'diag37', b'BAJO PESO'), (b'diag38', b'BARTOLINITIS+ EMBARAZO DE 21-22 SEMANAS DE GESTACION'), (b'diag39', b'BILIRUBINEMIA'), (b'diag40', b'BILLIRUBINEMIA'), (b'diag41', b'BIOPSIA'), (b'diag42', b'BIOPSIA  GLANGLIONAR AXILAR PB TB'), (b'diag43', b'BIOPSIA DE MAMA DERECHA'), (b'diag44', b'BIOPSIA EXSICIONAL'), (b'diag45', b'BNM'), (b'diag46', b'BNM + BRONCO ESPASMO SEC. + PCI +C.C'), (b'diag47', b'BRONCOESPASMO SEC. ASMA BRONQUIAL'), (b'diag48', b'BRONCONEUMONIA'), (b'diag49', b'BRONCONEUMONIA ADQUIRIDAD EN LA COMUNIDAD'), (b'diag50', b'BRONQUIOLITIS'), (b'diag51', b'BRONQUIOLITIS DESC.BNM')], max_length=100)),
                ('estado_Salud', models.CharField(choices=[(b'estsalud1', b'ESTABLE'), (b'estsalud2', b'DELICADO'), (b'estsalud3', b'MUY DELICADO'), (b'estsalud4', b'GRAVE'), (b'estsalud5', b'MUY GRAVE'), (b'estsalud6', b'DEFUNCION'), (b'estsalud7', b'ALTA'), (b'estsalud8', b'ALTA VOLUNTARIA'), (b'estsalud9', b'ALTA VIGENTE'), (b'estsalud10', b'ALTA VESPERTINA'), (b'estsalud11', b'ALTA POR MAXIMO BENEFICIO'), (b'estsalud12', b'ALTA POR REFERENCIA'), (b'estsalud13', b'ALTA POR FUGA'), (b'estsalud14', b'PREALTA')], max_length=100)),
                ('servicios', models.CharField(choices=[(b'servselect1', b'URGENCIAS GINECOLOGIA'), (b'servselect2', b'URGENCIAS'), (b'servselect3', b'TERAPIA INTENSIVA PEDIATRICA'), (b'servselect4', b'TERAPIA INTENSIVA'), (b'servselect5', b'PEDIATRIA / UCIN'), (b'servselect6', b'HOSPITALIZACION GINECOLOGICA'), (b'servselect7', b'HOSPITALIZACION'), (b'servselect8', b'CIRUGIA AMBULATORIA'), (b'servselect9', b'MORTORIO'), (b'servselect10', b'CONSULTA EXTERNA')], max_length=100)),
                ('cama', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Paciente')),
            ],
        ),
    ]
