# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_info_clinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospaciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='info_clinica',
            name='id',
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.Paciente'),
        ),
        migrations.AlterField(
            model_name='info_clinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.Paciente'),
        ),
    ]
