# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20160428_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domiciliopaciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='domiciliopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.Paciente'),
        ),
    ]
